version: '3.8'

services:
  api:
    platform: linux/amd64
    build: .
    container_name: dnd-back
    env_file:
      - .env
    ports:
      - '4000:3000'
    restart: unless-stopped
    command: ['pnpm', 'start:docker']
